import type { Metadata } from "next"
import { Inter, Antonio } from "next/font/google"
import "./globals.css";
import { Background, ToastNotification } from "@/components"
import { Providers } from "./provider"

const inter = Inter({
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap'
})

const antonio = Antonio({
  weight: ['300', '400', '500', '600', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-antonio",
})

export const metadata: Metadata = {
  title: "Rebel Empire",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="es">
      <body className={`${ inter.className } ${ antonio.variable }`} suppressHydrationWarning={ true }>
        <Providers>
          { children }
        </Providers>
        <Background/>
        <ToastNotification/>
      </body>
    </html>
  )
}
